// Generated by Wrangler on Sat May 11 2024 19:07:02 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	BUNDLE_ID: "com.example.gamecenter";
	ROOT_CA_URL: "https://knowledge.digicert.com/content/dam/kb/attachments/general/certificates/root/digicert-trusted-root-g4.cer";
	ICA_URL: "https://knowledge.digicert.com/content/dam/kb/attachments/general/certificates/ica/digicert-trusted-g4-code-signing-rsa4096-sha384-2021-ca1.cer";
	SILENCE_LOGGING: "false";
}
